#!/usr/bin/perl -w

use warnings;
use strict;

# Default length/number
my $len = 19;
my $num = 1;

# Pull in args and list usage
my $numargs = scalar @ARGV;
    if ($numargs == 0 || $ARGV[0] eq "-h") {
        print "Sal's Random Password Generator\n";
        print "-------------------------------\n";
        print "Usage: plpwgen <OPTIONS> [length] [number] (length and number optional)\n\n";
        print "OPTIONS (MUST SPECIFY ONE!):\n";
        print "-s               Add symbols to output (NOT FOR MYSQL!)\n";
        print "-a               Alphanumeric only\n";
        print "-p               Generate phpMyAdmin Blowfish secret (for cookie auth)\n";
        print "-w               Generate Wordpress encryption keys (wp-config.php)\n";
        print "-h               Display this usage information\n\n";
        print "If no length or number are defined, a default length of $len and number of $num will be used.\n";
        exit(0);
    }

# Check for the password/secret type
my $pwtype = $ARGV[0];

# If a length was supplied, override the default
if (defined $ARGV[1] && $ARGV[1] =~ /^\d+$/) {
    $len = $ARGV[1];
}

# If a number was supplied, override the default
if (defined $ARGV[2] && $ARGV[2] =~ /^\d+$/) {
    $num = $ARGV[2];
}

sub pwgen{
    # Custom definition for 'safe' symbols + alphanumeric
    my @symbols = ('-', '_', '!', '@', '#', '$', '%', '^', '&',
        '*', '/', '\\', '(', ')', '_', '+', '{', '}', '|', ':',
        '<', '>', '?', '=', 'A'..'Z', 'a'..'z', '0'..'9');

    # Alphanumeric-only option
    my @alphanumeric = ('A'..'Z', 'a'..'z', '0'..'9');

    # Time to do the actual generation
    my $pass;
    $pass = "";
    if ($_[1] eq "symbols") {
        $pass .= @symbols[rand @symbols] for 1..$_[0];
    } elsif ($_[1] eq "alphanumeric") {
        $pass .= @alphanumeric[rand @alphanumeric] for 1..$_[0];
    } else {
        exit(1);
    }
    return $pass;
}

# Generate random password(s) with symbols + alpha
if ($pwtype eq "-s") {
    my $count = 0;
    while ($count < $num) {
        my $pass = pwgen($len, "symbols");
        print "$pass\n";
        $count++;
    }
}

# Generate random password(s) with alphanumeric only
if ($pwtype eq "-a") {
    my $count = 0;
    while ($count < $num) {
        my $pass = pwgen($len, "alphanumeric");
        print "$pass\n";
        $count++;
    }
}

# Generate random phpMyAdmin Blowfish secret string
if ($pwtype eq "-p") {
    my $pass = pwgen("64", "symbols");
    print "$pass\n";
}

# Generate random encryption secrets for WordPress
if ($pwtype eq "-w") {
    my $pass1 = pwgen("64", "symbols");
    print "define('AUTH_KEY',\t\t'$pass1');\n";
    my $pass2 = pwgen("64", "symbols");
    print "define('SECURE_AUTH_KEY',\t'$pass2');\n";
    my $pass3 = pwgen("64", "symbols");
    print "define('LOGGED_IN_KEY',\t\t'$pass3');\n";
    my $pass4 = pwgen("64", "symbols");
    print "define('NONCE_KEY',\t\t'$pass4');\n";
    my $pass5 = pwgen("64", "symbols");
    print "define('AUTH_SALT',\t\t'$pass5');\n";
    my $pass6 = pwgen("64", "symbols");
    print "define('SECURE_AUTH_SALT',\t'$pass6');\n";
    my $pass7 = pwgen("64", "symbols");
    print "define('LOGGED_IN_SALT',\t'$pass7');\n";
    my $pass8 = pwgen("64", "symbols");
    print "define('NONCE_SALT',\t\t'$pass8');\n";
}
